spring.application.name=EzSender

server.port=8085
server.servlet.context-path=/ez-sender-api
spring.grpc.server.port=9001

spring.mongodb.uri=
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/public-key.pem

# rabbitmq config
spring.rabbitmq.addresses=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# exchange config
ez-sender.rabbitmq.exchange=ez.sender.rabbitmq.exchange
ez-sender.rabbitmq.email-queue=ez.sender.rabbitmq.email.queue
ez-sender.rabbitmq.push-queue=ez.sender.rabbitmq.push.queue
ez-sender.rabbitmq.sms-queue=ez.sender.rabbitmq.sms.queue

# fcm config
ezsender.fcm.key.store.path=fcm-key.json

#mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true